CREATE TABLE servers (
 id SERIAL,
 name VARCHAR(255) NOT NULL UNIQUE,
 -- TINYINT (0 255)
 -- 0 Not available
 -- 1 Available but not accesible (i.e. error 404 due a bad DNS configuration)
 -- 255 Available
 has_muc TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_irc TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_aim TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_gg TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_httpws TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_icq TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_msn TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_qq TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_sms TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_smtp TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_tlen TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_yahoo TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_jud TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_pubsub TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_pep TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_presence TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_newmail TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_rss TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_weather TINYINT UNSIGNED NOT NULL DEFAULT 0,
 has_proxy TINYINT UNSIGNED NOT NULL DEFAULT 0,
 -- Executions in wich this server were unavailable
 times_offline INT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (id),
 KEY (name)
);
